from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home-home'),
    path('about/', views.about, name='home-about'),
    path('contact/', views.contact, name='home-contact'),
    path('insert_patient', views.insert_patient,name='insert_pr'),
    path('insert_doctor', views.insert_doctor,name='insert_dr'),
    path('insert_admin', views.insert_admin,name='insert_adm'),
    path('insert_adm', views.insert_adm),
    path('insert_pt', views.insert_pt),
    path('insert_dr', views.insert_dr),
    path('mngmnt_show', views.mngmnt_show,name='mngmnt_show'),
    path('delete_patient/<int:id>', views.delete_patient,name='delete_patient'),
    path('delete_doctor/<int:id>', views.delete_doctor,name='delete_doctor'),
    path('edit_doctor/<int:id>', views.edit_doctor,name='edit_doctor'),
    path('edit_patient/<int:id>', views.edit_patient,name='edit_patient'),
    path('encode_dr/<int:id>', views.encode_dr,name='edit_doctor'),
    path('encode_pt/<int:id>', views.encode_pt,name='edit_patient'),
    path('encode_ad/<int:id>', views.encode_ad,name='edit_admin'),
    path('edit_admin/<int:id>', views.edit_admin,name='edit_admin'),
    path('admin_login', views.admin_login,name='admin_login'),
    path('admin_log', views.admin_log),
    path('doctor_login', views.doctor_login,name='doctor_login'),
    path('doctor_log', views.doctor_log),
    path('../../../doctor_show', views.doctor_show,name='doctor_show'),
    path('patient_login', views.patient_login,name='patient_login'),
    path('patient_log', views.patient_log),
    path('patient_show', views.patient_show,name='patient_show'),
    path('database', views.database,name='database'),
    path('pt_history/<int:doctor_id>/<int:patient_id>/', views.pt_history,name='patient_history'),
    path('pt_insert_history/<int:doctor_id>/<int:patient_id>/', views.pt_insert_history,name='pt_insert_history'),
    # path('patient_history_insert/<int:doctor_id>/<int:patient_id>/', views.patient_history_insert,name='patient_history_insert'),
    path('insert_pt_history_form/<int:doctor_id>/<int:patient_id>/', views.insert_pt_history_form,name='insert_pt_history_form'),
    # path('patient_history_view', views.patient_history_view,name='patient_history_view'),
    ]
