# Generated by Django 4.0.6 on 2022-08-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('mob', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
