# Generated by Django 4.0.6 on 2022-08-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='mob',
            field=models.CharField(max_length=15),
        ),
    ]
