# Generated by Django 4.0.6 on 2022-08-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_admin_mob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='add',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='bp',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='case',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
