# Generated by Django 4.0.6 on 2022-08-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_patient_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_history',
            name='doctor_id',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='patient_id',
            field=models.IntegerField(max_length=50),
        ),
    ]
