# Generated by Django 4.0.6 on 2022-08-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_patient_history_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_history',
            name='doctor_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_history',
            name='patient_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
