# Generated by Django 4.0.6 on 2022-08-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_patient_history_doctor_id_patient_history_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_history',
            name='doctor_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
