# Generated by Django 4.0.6 on 2022-08-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_patient_history_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_history',
            name='date',
            field=models.DateField(),
        ),
    ]
