# Generated by Django 4.0.6 on 2022-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_patient_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_history',
            name='medication',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='test_done',
            field=models.CharField(max_length=100),
        ),
    ]
